spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
        httpclient:
          wiretap: true
        httpserver:
          wiretap: true
      routes:
        - id: vcAppApi
          uri: lb://vcAppApi
          predicates:
            - Path=/api/**
          filters:
            - CustomAuthFilter
            - name: CircuitBreaker
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: demo
          uri: lb://WANDOKIM-DEMO-TEST
          predicates:
            - Path=/demo/**
          filters:            
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:            
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: vse_app
          uri: http://192.168.0.8:8710/
          predicates:
            - Path=/vse_app/**
          filters:            
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: vc_msc
          uri: lb://VC-MSC
          predicates:
            - Path=/vc_msc/**
          filters:
            - RewritePath=/vc_msc/(?<path>.*), /$\{path}
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost
